[package]
name = "bolt"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.18.2", features = ["extension-module"] }
ncollide2d = "0.33.0"
quadtree = { path = "../quadtree" }
collisions = { path = "../collisions" }

[lib]
crate-type = ["cdylib"]
