[package]
name = "bolt"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.18.3", features = ["extension-module"] }
ncollide2d = "0.33.0"
rand = "0.8.5"

collisions = { path = "../collisions" }
common = { path = "../common" }
quadtree = { path = "../quadtree" }
serialization = { path = "../serialization" }

[lib]
crate-type = ["cdylib"]
